### PR TITLE
issues/15: Disable get-installed-path

### PR DESCRIPTION
**Pull request by Peter-LaComb**
https://github.com/standard/standard-packages/issues/15

The target project fails for multiple comma-dangle issues. These issues are correct, there are dangling commas in the test file per the current rules.

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm, it seems like @tunnckoCore uses his own fork of standard which requires comma-dangle. Maybe it should be removed from the list since it isn't really standard style then?

**Review by aladdin-add — APPROVED** [review]

**Comment by Flet** [comment]
I think we can disable for now to stop the error. We can review disabled projects in the future and remove if needed.

**Review by Flet — APPROVED** [review]

**Comment by Flet** [comment]
merged but @feross will need to publish standard-packages or give access to some other folks to do it :)

**Comment by LinusU** [comment]
@feross would love if you could publish this, and potentially give access to some other people as well 😄

**Comment by Flet** [comment]
Looks like I got access to publish, so I did!

Published as `standard-packages@3.2.11`

**Pull request merged**
