### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by sonicdoe**
Updates `all.json` by running `npm run update`. The database was replicated on 2019-08-19 at around 18:30 UTC and had 1,055,401 docs.

```console
$ npm run update

> standard-packages@3.6.3 update …
> node tools/update.js

 
--------
SPECIFIC MODULES
--------

standard                              20840
snazzy                                 2178
eslint-config-standard                19767

--------
TOP 200
--------

1. mocha (using standard)                                178529
2. eslint                               149265
3. chai                                 107977
4. webpack                              101146
5. babel-core                            99906
6. typescript                            99811
7. lodash                                82628
8. babel-loader                          82602
9. react                                 78304
10. babel-cli                             75100
11. babel-eslint                          73352
12. jest                                  71606
13. babel-preset-es2015                   68806
14. rimraf                                65505
15. eslint-plugin-import                  64853
16. react-dom                             62100
17. @types/node                           57946
18. babel-preset-env                      56134
19. chalk                                 53708
20. gulp                                  53273
21. css-loader                            50884
22. tslint                                46115
23. sinon                                 45735
24. express                               45373
25. eslint-plugin-react                   45328
26. @babel/core                           44626
27. prettier                              42450
28. webpack-dev-server                    41593
29. request (using standard)                               41569
30. style-loader                          39378
31. @babel/preset-env                     37278
32. babel-preset-react                    37074
33. rollup                                34775
34. coveralls                             34635
35. commander (using standard)                             34111
36. grunt                                 33140
37. webpack-cli                           32996
38. istanbul                              32552
39. cross-env                             32475
40. node-sass                             31683
41. nyc (using standard)                                   31616
42. fs-extra (using standard)                              30748
43. file-loader                           30505
44. karma (using standard)                                 29865
45. husky                                 29614
46. ts-node                               29425
47. prop-types                            28874
48. babel-jest                            28241
49. html-webpack-plugin                   27771
50. async                                 26830
51. babel-preset-stage-0                  26747
52. eslint-plugin-jsx-a11y                26679
53. tape                                  26534
54. sass-loader                           26481
55. debug                                 26223
56. moment                                25950
57. vue                                   25263
58. babel-plugin-transform-runtime        24031
59. @types/jest                           23979
60. extract-text-webpack-plugin           23862
61. should                                23807
62. url-loader                            23459
63. tslib                                 23459
64. eslint-config-airbnb                  23365
65. autoprefixer                          23193
66. karma-chrome-launcher (using standard)                 22619
67. vue-template-compiler                 22526
68. eslint-plugin-promise                 22076
69. @babel/cli                            22049
70. bluebird                              21942
71. browserify                            21825
72. babel-runtime                         21565
73. rollup-plugin-node-resolve            21303
74. postcss-loader (using standard)                        21179
75. mkdirp                                21176
76. babel-register                        21026
77. standard (using standard)                              20840
78. glob                                  20560
79. eslint-plugin-standard (using standard)                20349
80. eslint-config-standard                19767
81. eslint-plugin-node                    19676
82. rxjs                                  19604
83. babel-polyfill                        19583
84. ava                                   19568
85. lint-staged                           19431
86. underscore                            19293
87. axios                                 19239
88. rollup-plugin-babel                   19068
89. ts-jest                               18873
90. rollup-plugin-commonjs                18153
91. babel-plugin-transform-object-rest-spread 17910
92. yargs (using standard)                                 17832
93. eslint-config-airbnb-base             17595
94. grunt-contrib-jshint                  17511
95. eslint-loader                         17087
96. karma-jasmine (using standard)                         16945
97. shelljs                               16836
98. gulp-rename                           16729
99. eslint-config-prettier                16585
100. semver                                16477
101. @types/mocha                          16377
102. babel-preset-stage-2                  16324
103. enzyme                                16222
104. core-js                               16116
105. colors                                16073
106. jquery                                16019
107. vue-loader                            15916
108. uglify-js                             15849
109. jasmine-core                          15444
110. sinon-chai                            15374
111. body-parser (using standard)                           15287
112. del                                   15278
113. gulp-uglify                           14762
114. gulp-util                             14738
115. eslint-plugin-prettier                14436
116. jshint                                14430
117. coffee-script                         14243
118. minimist                              14185
119. classnames                            14164
120. @angular/core                         14134
121. @types/react                          14068
122. inquirer                              13930
123. webpack-merge                         13918
124. uuid                                  13727
125. babel                                 13726
126. @babel/preset-react                   13633
127. less                                  13476
128. grunt-contrib-watch                   13200
129. zone.js                               13189
130. @angular/common                       12973
131. jsdom                                 12915
132. npm-run-all                           12892
133. @angular/compiler                     12815
134. grunt-contrib-clean                   12766
135. @types/chai                           12578
136. @babel/plugin-proposal-class-properties 12384
137. karma-mocha (using standard)                           12276
138. react-test-renderer                   12246
139. through2                              12152
140. babel-plugin-add-module-exports (using standard)       11930
141. @angular/platform-browser             11921
142. babel-plugin-transform-class-properties 11891
143. ora                                   11699
144. @types/jasmine                        11566
145. @angular/compiler-cli                 11459
146. dotenv (using standard)                                11445
147. nodemon                               11379
148. semantic-release                      11341
149. optimize-css-assets-webpack-plugin    11287
150. karma-webpack                         11221
151. redux                                 11105
152. uglifyjs-webpack-plugin               10869
153. karma-coverage (using standard)                        10846
154. ts-loader                             10791
155. karma-phantomjs-launcher (using standard)              10742
156. gulp-babel                            10733
157. @angular/platform-browser-dynamic     10724
158. eslint-plugin-flowtype                10695
159. cheerio                               10689
160. copy-webpack-plugin                   10557
161. less-loader                           10364
162. gulp-sourcemaps                       10346
163. yeoman-generator                      10115
164. grunt-contrib-uglify                  10074
165. codecov                               10053
166. supertest                              9892
167. flow-bin                               9865
168. gulp-mocha                             9701
169. @babel/runtime                         9639
170. chai-as-promised                       9567
171. cz-conventional-changelog              9514
172. gulp-concat                            9404
173. enzyme-adapter-react-16                9359
174. @angular/forms                         9090
175. @types/lodash                          9062
176. json-loader                            8976
177. q                                      8958
178. tslint-config-prettier                 8830
179. pre-commit                             8627
180. codelyzer                              8605
181. webpack-bundle-analyzer                8575
182. rollup-plugin-uglify                   8540
183. karma-sourcemap-loader                 8522
184. jasmine                                8475
185. @types/react-dom                       8360
186. js-yaml                                8341
187. gh-pages                               8336
188. co                                     8309
189. node-fetch                             8059
190. babelify                               8058
191. object-assign                          8029
192. eslint-plugin-babel                    8029
193. react-redux                            7940
194. react-addons-test-utils                7934
195. vue-style-loader                       7902
196. @angular/http                          7886
197. eslint-plugin-vue                      7874
198. case-sensitive-paths-webpack-plugin    7860
199. gulp-eslint                            7764
200. @babel/plugin-transform-runtime        7758
```

### CODE REVIEW

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
@sonicdoe Thanks for sending this PR and saving my bandwidth 😉I appreciate it!

**Comment by feross** [comment]
3.7.0

**Comment by sonicdoe** [comment]
Now that `all.json` is up to date, what do you think about updating `test.json` by copying the top repositories (as you explained in https://github.com/standard/standard-packages/pull/30#issuecomment-517962586)?

**Comment by feross** [comment]
@sonicdoe I'd support adding the top 100 ecosystem packages, and removing the currently disabled packages. The rest I'd like to keep since they've been in the test suite since the beginning so it's really useful to know if we make a rule change that causes one of them to fail.

**Pull request merged**
