### PR TITLE
Add top 100 packages to test

### PR DESCRIPTION
**Pull request by sonicdoe**
Adds the top 100 packages with the most dependents from `all.json` to `test.json`. Only includes packages which have not already been included and which depend on `standard` (and not on `eslint-config-standard`, for example). See https://github.com/standard/standard-packages/pull/32#issuecomment-530173455.

### CODE REVIEW

**Comment by feross** [comment]
Looks good. Is your plan to send PRs to the failing repos, or to just mark them as disabled in the test suite for now?

**Comment by sonicdoe** [comment]
Yes, my plan was to open pull requests but, if you’d prefer, I can also disable the failing packages and we can merge this right away.

**Comment by feross** [comment]
What if we merge this right away with failing repos marked as disabled, and then you can send PRs to un-disable repos as you get PRs landed on the disabled repos?

**Comment by sonicdoe** [comment]
I’ve updated the list (after rebasing onto `master`) and added a commit disabling all failing packages.

**Review by feross — APPROVED** [review]
LGTM

**Comment by feross** [comment]
3.8.0

**Pull request merged**
