### PR TITLE
Remove dormant repositories

### PR DESCRIPTION
**Pull request by sonicdoe**
Removes the following test repositories where the last push is over four years ago:

- [shama/base-element](https://github.com/shama/base-element) (July 2015)
- [watson/hash-index](https://github.com/watson/hash-index) (July 2015)
- [yoshuawuyts/from2-string](https://github.com/yoshuawuyts/from2-string) (July 2015)
- [mafintosh/sorted-union-stream](https://github.com/mafintosh/sorted-union-stream) (July 2015)
- [Jam3/tap-dev-tool](https://github.com/Jam3/tap-dev-tool) (June 2015)
- [junosuarez/sanitycheck](https://github.com/junosuarez/sanitycheck) (June 2015)
- [hayes/just-debounce](https://github.com/hayes/just-debounce) (June 2015)
- [wilmoore/apply-or.js](https://github.com/wilmoore/apply-or.js) (May 2015)
- [shama/attach-css](https://github.com/shama/attach-css) (May 2015)
- [mafintosh/cyclist](https://github.com/mafintosh/cyclist) (May 2015)
- [mightyiam/mightyiam.js](https://github.com/mightyiam/mightyiam.js) (May 2015)
- [mafintosh/random-iterate](https://github.com/mafintosh/random-iterate) (April 2015)
- [mafintosh/airpaste](https://github.com/mafintosh/airpaste) (April 2015)
- [wilmoore/rerun-script](https://github.com/wilmoore/rerun-script) (April 2015)
- [Jam3/gl-blend-demo](https://github.com/Jam3/gl-blend-demo) (April 2015)
- [npm-dom/dom-stub](https://github.com/npm-dom/dom-stub) (April 2015)
- [pbrinkmeier/reeal](https://github.com/pbrinkmeier/reeal) (February 2015)

### CODE REVIEW

**Comment by bcomnes** [comment]
Some of these, while dormant, are still very much useable and useful.  They still might be useful data points for how standard changes affect packages that are 'done'.

**Comment by sonicdoe** [comment]
I agree that these packages can still be useful, however, they are also likely to fail when standard intentionally introduces breaking changes. Of course, usually, when introducing new rules, pull requests are sent upstream, however, I’d argue that the likelihood of them being merged is quite low since these packages haven’t been updated in such a long time. In fact, they already haven’t kept up with the last nine major releases (most of these packages are on standard v4 or earlier).

Do you think there’s some sort of middle ground here? If we keep them, I feel like we’ll just end up disabling all of them at some point (and quite a lot of them already are).

**Comment by LinusU** [comment]
> Do you think there’s some sort of middle ground here?

Maybe we could submit PRs to them to bring Standard to the latest version? and if they are accepted we know that they are responding to PRs and we could keep them on the list ☺️ 

I could help sending them out!

**Comment by sonicdoe** [comment]
I like the intention but is opening that many pull requests feasible? We are probably talking about hundreds of repositories here; `test.json` alone contains 411 packages.

By the way, when should a repository be included in `test.json` (as opposed to simply being listed in `all.json`)? Furthermore, what’s the purpose of keeping disabled packages in there (currently, 259 of 411 packages in `test.json` are disabled)?

**Comment by feross** [comment]
> what’s the purpose of keeping disabled packages in there (currently, 259 of 411 packages in `test.json` are disabled)

The idea is to re-enable them later when they update the version of `standard` that they use. I'd rather go with with @LinusU's suggestion to at least attempt to bump the `standard` dep before removing them from the list.

> By the way, when should a repository be included in test.json (as opposed to simply being listed in all.json)?

The `test.json` file was originally produced by listing the top ~400 repos that use `standard` based on number of npm dependents. I'd like to update the list to include newer packages, but that's blocked on https://github.com/standard/standard-packages/issues/27 at the moment.

**Comment by feross** [comment]
I just un-disabled all the previously disabled packages which are now passing: https://github.com/standard/standard-packages/commit/69d6a7969c0e7561147344c9d899afee097a442e

@sonicdoe If you want to edit this PR to remove the packages which are four year old **and** also disabled, that's fine. But let's not preemptively disable working packages as that loses information that we want to have when considering new rules.

**Comment by sonicdoe** [comment]
> The `test.json` file was originally produced by listing the top ~400 repos that use `standard` based on number of npm dependents. I'd like to update the list to include newer packages, but that's blocked on #27 at the moment.

In that case, I’d suggest to first update the list (after resolving #27) and afterwards open pull requests in those repositories where `standard` is outdated.

**Comment by sonicdoe** [comment]
I’m closing this because #35 removed all currently disabled packages.

**Pull request closed without merging**
