### PR TITLE
Disable more failing packages

### PR DESCRIPTION
**Pull request by novemberborn**

### CODE REVIEW

**Comment by LinusU** [comment]
It would be nice to submit pull requests to these repos, I might take a stab at that this week if I get the time

**Comment by novemberborn** [comment]
I suspect these might have been failing due to https://github.com/eslint/eslint/commit/56a662b4ebccf9e50acddcec38816060c89e8f5b.

**Comment by LinusU** [comment]
Yes, probably, we've been seeing a lot of those breaking our builds...

**Comment by feross** [comment]
Thanks for the PR. Sorry it took so long to merge. It's stale now, so I'll close it.

**Pull request closed without merging**
